### ISSUE TITLE
`prepare_ae_specific()` pop up error if `var` variable has `NA`

### ISSUE THREAD

**Issue by wangben718** [Merck/metalite.ae#100]

**Comment by LittleBeannie** [comment]
Analysis population type:
#>     name        id    group var       subset                         label
#> 1 'apat' 'USUBJID' 'TRT01A'     SAFFL == 'Y' 'All Participants as Treated'

Better to give an error message when group var is empty.

**Comment by elong0527** [comment]
Is this issue resolved? If not, could you provide an example code?
