### ISSUE TITLE
ae_summary.Rmd

### ISSUE THREAD

**Issue by elong0527** [Merck/metalite.ae#115]
Provide additional instruction in `ae_summary.Rmd`

There are optional functions to extend the analysis if needed.

- **TODO** `extend_ae_specific_inference`: add risk difference inference results based on M&N method.

**Comment by wangben718** [comment]
Is this example what you want? https://github.com/Merck/metalite.ae/blob/7d2d00fd022c1cf342cf5ce0409c883955cc3bae/vignettes/ae-summary.Rmd#L143

**Comment by elong0527** [comment]
Thanks!
