### ISSUE TITLE
copy from metalite #16

### ISSUE THREAD

**Issue by fb-elong** [Merck/metalite.ae#118]
https://github.com/Merck/metalite/issues/16

metalite/default_parameter_ae.R updates required for the below for the ae0summary

"with no adverse event" category is not present in ae0summary r table, adam_mapping in metalite to be updated to add it
"grade 3-4 adverse event" not present in adam_mapping.
disc0ser0rel subset condition has to be updated in adam_mapping to add drug-related
dtc0rel subset condtion need to be updated with aesdth=="Y" instead of aesdtc == "Y"
discontinued drug1(ACN1), drug2(ACN2) categories need to be added
dose modification categories need to be added.

**Comment by wangben718** [comment]
It has already been resolved.
