### ISSUE TITLE
Copied from metalite #16 comments

### ISSUE THREAD

**Issue by fb-elong** [Merck/metalite.ae#119]
metalite.ae::prepare_ae_summary update and under review for "with no adverse event" category.
"grade 3-4 adverse event" added to default parameter list. PR merged.
disc0ser0rel subset condition update. PR merged.
dtc0rel subset condition update. PR merged.
@ginnaram Discontinued drug1/drug 2 and dose modification categories are sub-categories within bigger category. Will have to re-visit this later.

**Comment by elong0527** [comment]
The action item is unclear. 

Let's close this one and open other issues.
