### ISSUE TITLE
format_ae_listing.R format

### ISSUE THREAD

**Issue by elong0527** [Merck/metalite.ae#12]
- [x] Move copyright information to he header (e.g. https://github.com/Merck/metalite.ae/blob/main/R/fmt.R)
- [x] `propercase`: would `tools::toTitleCase` meet the goal? 
- [x] Avoid harding coding variable name in the logic. please create a variable mapping and save in metadata. Then use left side to implement the logic.
   - Example: https://github.com/Merck/metalite.ae/blob/main/R/prepare_ae_specific.R
   - Reference: https://merck.github.io/metalite/articles/adam-mapping.html
- [x] Please consider to use `switch` function to avoid nested if else. https://github.com/Merck/metalite.ae/blob/main/R/format_ae_listing.R#L143

**Comment by nanxstats** [comment]
Also: use `drop = FALSE` when subsetting data frames. https://adv-r.hadley.nz/subsetting.html#simplify-preserve

**Comment by wangben718** [comment]
reesolve issue except Avoid harding coding variable name in the logic. Will do after I updated the interactive report this week.
