### ISSUE TITLE
Release metalite.ae 0.1.1

### ISSUE THREAD

**Issue by nanxstats** [Merck/metalite.ae#126]
First release

- [x] Proof read `Title:` and `Description:` and ensure they are informative
- [x] Check that all exported functions have `@return` and `@examples`
- [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
- [x] Review [extrachecks](https://github.com/DavisVaughan/extrachecks)
- [ ] `usethis::use_cran_comments()` (optional)

Prepare for release

- [ ] Check current CRAN check results
- [ ] Check licensing of included files
- [ ] Review pkgdown reference index for, e.g., missing topics
- [ ] Bump version
- [ ] Update `cran-comments.md` (optional)
- [ ] Update NEWS.md
- [ ] Review pkgdown website
- [ ] `urlchecker::url_check()`
- [ ] Check with local machine
- [ ] Check with GitHub Actions
- [ ] Check with win-builder

Submit to CRAN

- [ ] Draft GitHub release
- [ ] Submit to CRAN via web form
- [ ] Approve emails

Wait for CRAN

- [ ] Accepted :tada:
- [ ] Post on r-packages mailing list
- [ ] Tweet

**Comment by LittleBeannie** [comment]
Comments from CRAN reviewers:

- [ ] Some code lines in examples are commented out. Please never do that. Ideally find toy examples that can be regularly executed and checked. Lengthy examples (> 5 sec), can be wrapped in \donttest{}. Examples in comments in: `prepare_ae_specific_subgroup.Rd`
- [ ] Please write references in the description of the DESCRIPTION file in the form authors (year) <https:...>
- [ ] Please fix and resubmit.
