### ISSUE TITLE
duplicated n_subject function

### ISSUE THREAD

**Issue by elong0527** [Merck/metalite.ae#128]
The n_subject function is an internal function both in `metalite` and `metalite.ae`. 

Should we export `n_subject` from `metalite` and remove `n_subject` from `metalite.ae`?

**Comment by nanxstats** [comment]
I'd say yes? If it's considered universally useful. It's your decision.

**Comment by elong0527** [comment]
It will require a newer version of `metalite` on CRAN, let's hold it for future version :)

**Comment by fb-elong** [comment]
@wangben718 here is the task related to `n_subject`
