### ISSUE TITLE
Suggestion: `collect_ae_listing`

### ISSUE THREAD

**Issue by elong0527** [Merck/metalite.ae#14]
- [x] Package should not load itself in example code https://github.com/Merck/metalite.ae/blob/main/R/collect_ae_listing.R#L26
- [x] Why would not we directly use `outdate` in the logic. 
- [x] Avoid of using `SAFFL` directly in the logic. People can use different flag for analysis. It should be handled as https://github.com/Merck/metalite.ae/blob/main/R/prepare_ae_specific.R#L54-L57 to get population and observation data for analysis purpose. 
- [x] Please use `"` and `'` consistently https://github.com/Merck/metalite.ae/blob/main/R/collect_ae_listing.R#L35

**Comment by wangben718** [comment]
Hi Yilong @elong0527, this issue has been resolved by my recent PR.

**Comment by elong0527** [comment]
If you are referring #22, please also try to address the comments in the PR
