### ISSUE TITLE
Add Exposure-Adjusted Adverse Event Summary table

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/metalite.ae#142]
![image](https://github.com/Merck/metalite.ae/assets/43153957/b6f81385-d079-4547-8a83-f51dd38d31fd)

**Comment by nanxstats** [comment]
Has this been resolved by a specific PR (please add link) or is this still being planned, or not planned anymore?

**Comment by nanxstats** [comment]
Hey @wangben718 I see #146 was only closed without being merged. So I just want to double check if this was actually resolved? If so, can we link the specific PR(s) here so it's easier when preparing release news.

**Comment by wangben718** [comment]
Hi @nanxstats , this issue is related to #180  and #174 .
