### ISSUE TITLE
Add examples in `format_ae_specific_subgroup`

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/metalite.ae#147]
- [x] We do not have `@examples` in https://github.com/Merck/metalite.ae/blob/subgroup_analysis/R/format_ae_specific_subgroup.R. 
- [x] the following code doesn't work
```
meta_ae <- meta_ae_example()
prepare_ae_specific_subgroup(
  meta_ae,
  population = "apat", observation = "wk12",
  parameter = "rel", subgroup_var = "age",
  display_subgroup_total = T
  ) |>
  format_ae_specific_subgroup()
```

- [x] Shall we change the adsl$RACE variable into sentence case when we display the table?

- [ ] some interactive thought for baseline char table: 

- https://glin.quarto.pub/observable-reactable/#using-reactable-to-filter-observable-charts
- https://glin.github.io/reactable/articles/custom-filtering.html#range-filter
- https://glin.github.io/reactable/articles/custom-filtering.html#range-filter-react

@wangben718 , please help assign the mentioned minor issues to the team members according to their availability.

**Comment by nanxstats** [comment]
A few style improvements needed:

- Also missing the `@return` field in the documentation.
- Use `message()` instead of `print()` to output messages.
- All `@param`s should use sentence case and end with a full stop, with two spaces of extra indention for descriptions spanning over multiple lines: https://style.tidyverse.org/documentation.html

**Comment by elong0527** [comment]
>  Shall we change the adsl$RACE variable into sentence case when we display the table? 

It is an example dataset, we can keep it as is. 

>  some interactive thought for baseline char table:

Interactive features will require more efforts. Feel `forestly` already cover most use cases. 
If needed, how about we put interactive features in another R package that depends on `metalite.ae`?

**Comment by elong0527** [comment]
> A few style improvements needed:
> 
> * Also missing the `@return` field in the documentation.
> * Use `message()` instead of `print()` to output messages.
> * All `@param`s should use sentence case and end with a full stop, with two spaces of extra indention for descriptions spanning over multiple lines: https://style.tidyverse.org/documentation.html

create a new issue #157 to address it separately.
