### ISSUE TITLE
Design Pattern: using `rlang::eval_tidy()` in a secure way. 

### ISSUE THREAD

**Issue by fb-elong** [Merck/metalite.ae#153]
Is `rlang::eval_tidy()` evaluating arbitrary input expressions? That would create a security vulnerbility, as the expression can be malicious.

**Comment by nanxstats** [comment]
I did some preliminary research and wrote a [draft](https://gist.github.com/nanxstats/cb743265f7d9102bcb060389e7512c6b).

The basics seem clear but I wonder if there is a more authoritative guide on this topic.

**Comment by nanxstats** [comment]
We can close this for now. We can analyze the use cases on case by case basis. It's a bit challenging to write a secure evaluation guide from a non-rlang author's perspective.
