### ISSUE TITLE
Grant contribution access

### ISSUE THREAD

**Issue by ruchitpatel2002** [Merck/metalite.ae#17]
@nanxstats would you grant permission to  @ginnaram13 so he can contribute to independent testing.

**Comment by ruchitpatel2002** [comment]
@nanxstats Also grand permission to @LittleBeannie

**Comment by nanxstats** [comment]
Cool - I checked and @ginnaram13 and @LittleBeannie already have write permission to this repo.

**Comment by ruchitpatel2002** [comment]
Thank you very much Nan for checking.
