### ISSUE TITLE
Question about function rate_compare_sum

### ISSUE THREAD

**Issue by MargheAnna** [Merck/metalite.ae#170]
First of all, many thanks for this useful package!
My question is related to rate_compare_sum function, line 261

z_score <- (r_diff - delta) / sqrt(sum(var_w))

In the paper the formula is the following (of course this is the square of the one in the program) :
![image](https://github.com/Merck/metalite.ae/assets/144261701/1752e28c-7199-44e1-b804-41441455dad5)

 
Why isn’t delta multiplied by the sum of weights? 
If sum of weights is equal to 1, this wouldn’t affect the calculation but with equal weights, for example, as their sum is different from 1, this would affect the value. Have you further simplified the formula in the paper?

Many thanks!!

**Comment by elong0527** [comment]
Thanks for reading the code carefully!

It is just to reduce unnecessary calculations.


If you check the definition of the weight in line 252-256, the summation is 1 in each cases.

**Comment by MargheAnna** [comment]
Many thanks for your quick reply!
I still have a question if possible, how do equal weights sum up to 1 if for each strata the weight is 1 and not 1/number of strata? 

Line 253
equal = rep(1, length(strata))

**Comment by elong0527** [comment]
Good catch, for equal weight that's an unique case. If you put 1 back to the formula, you will see the values are all cancelled out.

I acknowledged it will be more clear if we follow the formula exactly, but I will keep the code as is given the numerical values are the same in equal weight.

**Comment by MargheAnna** [comment]
Ah! I see, it makes sense! Sorry for my naive questions, absolutely keep the code as is, I should have tried to do the calculations. Many thanks for the quick and detailed replies!

**Comment by MargheAnna** [comment]
Hello again, apologies to ask again when I said that I understood; this morning I had a look again with fresh mind. I know I may be annoying and you're for sure busy with other things but I still have a doubt if you can address it, I promise it will be my last question. 
I agree with you that with equal weights any constant number is fine since you will simplify numerator and denominator but I think that the sum should be kept for delta (or delta*number of strata).
![image](https://github.com/Merck/metalite.ae/assets/144261701/e42aa8a4-152c-4b66-93a7-fc1956081983)
Here below I wrote few lines of code to test the formula in the function and the one with the sum of weights and I do get different results 

`r1<-c(0.2,0.7,0.3)
r0<-c(0.1,0.5,0.8)
delta<-0.2
w<-c(1,1,1)
vart<-c(1,2,3)

r1_w <- r1 * w
r0_w <- r0 * w
var_w <- w^2 * vart
r_diff <- (sum(r1_w) - sum(r0_w))
z_score <- (r_diff - delta) / sqrt(sum(var_w))
#-0.1632993

z_score_MA<-(r_diff-sum(w)*delta) / sqrt(sum(var_w))`
#-0.3265986

**Comment by nanxstats** [comment]
Since this issue has become stale for 5 months, I'm closing it for now. In case further follow ups are needed, please feel free to open a new one and tag this issue. If real issues are discovered, please send a pull request.
