### ISSUE TITLE
Independent Testing for fmt_est.R

### ISSUE THREAD

**Issue by ruchitpatel2002** [Merck/metalite.ae#19]

**Comment by LittleBeannie** [comment]
Test plan:
 
`x <- iris |>summarise(mean = mean(Petal.Length), sd = sd(Petal.Length))`
- `fmt_est(x$mean, x$sd)`  -> `"  3.8 ( 1.8)"`
- `fmt_est(x$mean, x$sd, digits = c(2,2))` -> `"  3.76 ( 1.77)"`

**Comment by burlave** [comment]
@LittleBeannie : Could you please let me know how width options is expected in the output?
 expect_equal("1.20 (0.762)", fmt_est(x$mean, x$sd, digits = c(2,3), width = c(1, 4)))
 expect_equal("1.20 (0.762)", fmt_est(x$mean, x$sd, digits = c(2,3), width = c(2, 4)))
 expect_equal("1.20 (0.762)", fmt_est(x$mean, x$sd, digits = c(2,3), width = c(4, 3)))
I tried with different values for width and I didn't see any change in the output. Please let me know if I miss anything.

**Comment by LittleBeannie** [comment]
Please refer to the reference of `fmt_est()` in https://merck.github.io/metalite.ae/reference/fmt_est.html. 
If you take a look at the source code of `fmt_est()`, you will find the `width= ...` is used in `formatC()`. 
`formatC()` is formats numbers individually and flexibly using C style format specifications. see examples in https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/formatC. If you play with the examples, you will find the usage of `width=...`
