### ISSUE TITLE
Independent Testing for extend_ae_specific.R

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/metalite.ae#24]
Hi @elong0527, could you please list the test plan of these functions?

**Comment by elong0527** [comment]
Could you refer the examples in https://merck.github.io/metalite.ae/articles/ae-specific.html ? 

In general, we want to confirm the values are accurate in certain edge cases. e.g with missing value. 

@BrianLang, please also suggest few test cases for `extend_ae_specific_duration` and `extend_ae_specific_events` as it is relevant to your use cases.

**Comment by LittleBeannie** [comment]
- Test  plan of `extend_ae_specific_inference`: 
  + The CI matches that from SAS
  + Throw error when `ci = ...` is negative number.

- Test  plan of `extend_ae_specific_duration`: 
   + The average duration matches that from SAS
   + Throw errors when `duration_var` is a string vector of length >1

- Test  plan of `extend_ae_specific_events`: 
   + The average number of events matches that from SAS

**Comment by BrianLang** [comment]
Can we please have a review of the PR #81
