### ISSUE TITLE
Independent Testing for prepare_ae_specific.R

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/metalite.ae#30]
Test plan:
- The output is a list
- check if each component:
    + population: match the expectation
    + observation: match the expectation
    + parameter: match the expectation
    + n: match SAS
    + order: match the expectation
    + group: match the expectation
    + reference_group: match the expectation
    + prop: match SAS
    + diff: match SAS
    + name: match the expectation
    + diff: match SAS
    + n_pop: match SAS
    + name: match the expectation

**Comment by srnep** [comment]
![image](https://user-images.githubusercontent.com/103936599/174331032-8db03e3c-8925-4bbc-8647-867da840425a.png)

**Comment by LittleBeannie** [comment]
@srnep , please list more information about `test_meta_specification`. I guess the error is caused by the TRT01A, which is not a leveled factor.

**Comment by LittleBeannie** [comment]
The error is because you didn't run the following code:
```
adae$TRT01A <- factor(adae$TRT01A, levels = c("Placebo", "Xanomeline Low Dose", "Xanomeline High Dose"))
```

Besides, I revised the code of `prepare_ae_summary`. Please take a look at the diff 👉 https://github.com/Merck/metalite.ae/blob/32-independent-testing-for-prepare_ae_summaryr/tests/testthat/test-independent-testing-prepare_ae_summary.R
