### ISSUE TITLE
Independent Testing for prop_test_mn.R

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/metalite.ae#33]
Test plan:
- Test if the output matches that from SAS under 
    + different test types (one-sided or two-sided) 
    + different alpha

**Comment by wangben718** [comment]
Hi Yilong @elong0527:

Do we still need `prop_test_mn()`? I think we did not use it in our package and functionality is fulfilled by other functions.

Ben

**Comment by elong0527** [comment]
You may put this function in test folder to test the other function we developed.
