### ISSUE TITLE
Independent Testing for tlf_ae_specific.R

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/metalite.ae#37]
Test if the generated rtf table matches that from SAS. (`r2rtf::r2rtf_adsl` and `r2rtf::r2rtf_adae` can be used as test dataset)

**Comment by BrianLang** [comment]
can we make sure that we also are running `tlf_ae_specific()`  on `extend_ae_specific_XX()` processed tables and those outputs are as expected?

**Comment by LittleBeannie** [comment]
> can we make sure that we also are running `tlf_ae_specific()` on `extend_ae_specific_XX()` processed tables and those outputs are as expected? would that be part of this testing?

The current test doesn't cover `extend_ae_specific_xxx()`. Please reach out to @howardbaek and @srnep to check if they have additional time flexibility for this.
