### ISSUE TITLE
a tiny bug in `fmt_ci()`

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/metalite.ae#46]
`fmt_ci` returns nothing (Thanks for @wangben718  pointing it out). 
See line #92 in https://github.com/Merck/metalite.ae/blob/main/R/fmt.R#L92.
Here is an example for debugging:
```
metalite.ae::fmt_ci(1,2)
```

Please use branch #46 to fix the bug.

**Comment by elong0527** [comment]
Thanks, seems a simple fix. Would you mind to create a PR?
