### ISSUE TITLE
Complete `tlf_ae_specific` development

### ISSUE THREAD

**Issue by BrianLang** [Merck/metalite.ae#84]
`tlf_ae_specific` is incomplete.

In particular, it must have logic to calculate headers and column bounds on the basis of various specifications from 
`format_ae_specific`. The specifications which are not yet supported are `diff_XX` (between-group statistics), `events` and `dur`.  

#82 has fixes for `events` and `dur` and could be extended to address `diff_XX` specification. 

- [x] implement support for `events` and `dur`
  - [x] headers
  - [x] column separators
- [x] implement support for `diff_xx`
  - [x] headers
  - [x] column separators
- [x] testing
  - [x] diff_xx variables
    - [x] **w/ total**
    - [x] **w/o total**
    - [x] w/ total and dur
    - [x] w/ dur
  - [x] events
    - [x] **w/ total**   
    - [x] **w/o total**   
    - [x] w/ total and dur
    - [x] w/ dur
  - [x] n and prop
    - [x] w/ total   
    - [x] w/o total
    - [x] only n
  - [x] arguments
    - [x] **rel_width_col**

**Comment by BrianLang** [comment]
I will put together a PR for this based on the #82 fix.

**Comment by BrianLang** [comment]
done

**Comment by nanxstats** [comment]
Wow, this looks complicated! Thanks for the fix 👍

**Comment by BrianLang** [comment]
Cheers,

If you look at the PR I'd be glad to hear some feedback about the refactoring and implementation! 

I ended up dropping most all of the tests after recognizing that the largest tables can test the smallest ones.
